sudo: false
language: php
php:
- 7.2
- 7.3
install:
- nvm install 10
- npm install -g yarn
- yarn install
- composer install
script:
- ".travis-build/phplint ."
- vendor/bin/phpunit -v
after_script:
- vendor/bin/test-reporter
after_success:
- npm run build
- rm -rf node_modules
- tar -czf ExperientialLearningInventory.tar.gz *
notifications:
  email: false
deploy:
  provider: releases
  api_key:
    secure: dOGl6E0VhVqe5goFLQCqrC/a7HUEgg3+H0CA+F3NtK/LHwcxEdqnu41QMs8VhRI1Tk9Ja7gXZFoo4HeeI0/7jZE0NjVcFPZl33gDLwHUOhKuXkT3mQKJ7KsAhQPgdqPtX3JFfbm6ZH/bVCDGteJyS+1ml8p8TFb3eqYw0+uFRChKS+HYz2eRfXm+Qs4xheCYnngzG/ASEtp21VnYrm7vpONR7NbllaNYaOvidp1hTeb5pc22loor43kSPIoiCbedr0N/oANUdE9fYxWZlUfR6RkjCQ1KIV/B5vsiTxhEtUQKl+NM5tNCFnrBPxFJTJ/2DUhH6rw0m/DSjtSyAB4mfenEeFnfcbcIfYdxKKfHL2pqIWwTOP0Df5UsRLSAHG3weqYyNCjuZOuMF7xaisiZX6HjdyFMrudO7+gIvLcnSKwnayv/ilY50lL76lS/6e4fUoRsBCO/QER5PcD4kkLxVOwOZBvVaDK8rA6cKddmxsaQx5mkbuPCbS0KHAJQRJwV4KRdfN95iOB9z5Xxe/jd2xREZIrR2uZcrkuiYVkDlBQ1ktseks1Fmv93JlWzNxVdbuEJcSKT7SJ6lzXwaLVgfpfm3IcgZYb+5CvcSw6ljZl5btPkx7PlDi4xNA4ly+i1Nz2D0jeYi4dU1sWzxQ2QdJjHq8Dd3XpVY12jUxwEkaE=
  file: ExperientialLearningInventory.tar.gz
  on:
    repo: BrownBook/ExperientialLearningInventory
    branch: master
    tags: true
  skip_cleanup: 'true'
  overwrite: 'true'
