sudo: false
language: php
php:
    - 7.2
    - 7.3

install:
    - nvm install 6
    - npm install -g yarn
    - yarn install
    - composer install

script:
- ".travis-build/phplint ."
- vendor/bin/phpunit -v

after_script:
- vendor/bin/test-reporter

after_success:
    - npm run build
    - rm -rf node_modules
    - tar -czf ExperientialLearningInventory.tar.gz *

notifications:
  email: false

#deploy:
#  provider: releases
#  skip_cleanup: true
#  api_key:
#    secure: lPFLb25Gwb/X8aBiNQ4Mz2b5XBviLLg0Zp7Rgoj9Xc8ZwFlNw/JqnoLKnZFljXBW38yUt3fEyxUGFrImLDbwwzN6+1iOfjVrCrIYdJtKf1CoF9Mq1+bjUbz8wIXfvdIvuF+VxFWFcbFtUiTiVpeDkSBwWXLaazCZWQJZpWYZuQc=
#  file: Internshipinventory.tar.gz
#  overwrite: true
#  on:
#    repo: AppStateESS/InternshipInventory
#    branch: master
#    tags: true
